server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hugang999/microservicecloud-config.git
          #uri: git@github.com:hugang999/microservicecloud-config.git   #GitHub上面的git仓库名称
